services:
  flask_app:
    build: ./src/app
    container_name: flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mlflow_server

  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: mlflow_user
      POSTGRES_PASSWORD: mlflow_pass
      POSTGRES_DB: mlflow_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
    volumes:
      - ./minio/data:/data

  mlflow_server:
      build: .
      container_name: mlflow_server
      environment:
        MLFLOW_TRACKING_URI: postgresql+psycopg2://mlflow_user:mlflow_pass@postgres/mlflow_db
        MLFLOW_ARTIFACT_URI: http://minio:9000/mlflow
      ports:
        - "5001:5000"
      depends_on:
        - postgres
        - minio
      volumes:
        - ./mlruns:/mlflow/mlruns
      command: mlflow server --backend-store-uri postgresql+psycopg2://mlflow_user:mlflow_pass@postgres/mlflow_db --default-artifact-root http://minio:9000/mlflow --host 0.0.0.0 --port 5000