version: '3.8'
services:
  mlflow_server:
    image: mlflow:latest
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow_server:5000
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
  fastapi_app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mlflow_server