stages:
  prepare_data:
    cmd: python src/data_preparation.py --input_path data/raw/data.csv --output_dir data/processed --params params.yaml
    deps:
      - data/raw/data.csv
      - src/data_preparation.py
      - params.yaml
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv
    params:
      - prepare_data
  train_model:
    cmd: python src/train_model.py --X_train_path data/processed/X_train.csv --y_train_path data/processed/y_train.csv --params params.yaml
    deps:
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - src/train_model.py
      - params.yaml
    outs:
      - models/best_model.pkl
    params:
      - train_model
  evaluate_model:
    cmd: python src/evaluate_model.py --X_test_path data/processed/X_test.csv --y_test_path data/processed/y_test.csv --model_path models/best_model.pkl
    deps:
      - data/processed/X_test.csv
      - data/processed/y_test.csv
      - models/best_model.pkl
      - src/evaluate_model.py
    outs:
      - metrics/evaluation.json
      - data/predictions/predictions.csv